// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sf/substreams/foundational-store/service/v1/service.proto

package pbstore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Store_Get_FullMethodName    = "/sf.substreams.foundational_store.v1.Store/Get"
	Store_GetAll_FullMethodName = "/sf.substreams.foundational_store.v1.Store/GetAll"
)

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =================================================================================================
// DEPRECATED SERVICE - DO NOT USE FOR NEW IMPLEMENTATIONS
// =================================================================================================
// This entire v1 service is DEPRECATED and will be removed in a future version.
// Use sf.substreams.foundational_store.service.v2 instead.
//
// Migration Guide:
// - Replace Store service with sf.substreams.foundational_store.service.v2.Store
// - Replace Get() calls with v2.Store.Get()
// - Replace GetAll() calls with v2.Store.Get() using multiple keys
// - Update message types to use sf.substreams.foundational_store.model.v2 types
//
// The v1 service provides basic key-value store operations for Substreams modules.
// All methods and messages in this service are deprecated and should be replaced with their v2 equivalents.
type StoreClient interface {
	// DEPRECATED: Use sf.substreams.foundational_store.service.v2.Store.Get instead.
	// This method will be removed in a future version.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// DEPRECATED: Use sf.substreams.foundational_store.service.v2.Store.Get instead with multiple keys.
	// This method will be removed in a future version.
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Store_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, Store_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
// All implementations must embed UnimplementedStoreServer
// for forward compatibility.
//
// =================================================================================================
// DEPRECATED SERVICE - DO NOT USE FOR NEW IMPLEMENTATIONS
// =================================================================================================
// This entire v1 service is DEPRECATED and will be removed in a future version.
// Use sf.substreams.foundational_store.service.v2 instead.
//
// Migration Guide:
// - Replace Store service with sf.substreams.foundational_store.service.v2.Store
// - Replace Get() calls with v2.Store.Get()
// - Replace GetAll() calls with v2.Store.Get() using multiple keys
// - Update message types to use sf.substreams.foundational_store.model.v2 types
//
// The v1 service provides basic key-value store operations for Substreams modules.
// All methods and messages in this service are deprecated and should be replaced with their v2 equivalents.
type StoreServer interface {
	// DEPRECATED: Use sf.substreams.foundational_store.service.v2.Store.Get instead.
	// This method will be removed in a future version.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// DEPRECATED: Use sf.substreams.foundational_store.service.v2.Store.Get instead with multiple keys.
	// This method will be removed in a future version.
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	mustEmbedUnimplementedStoreServer()
}

// UnimplementedStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServer struct{}

func (UnimplementedStoreServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStoreServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedStoreServer) mustEmbedUnimplementedStoreServer() {}
func (UnimplementedStoreServer) testEmbeddedByValue()               {}

// UnsafeStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServer will
// result in compilation errors.
type UnsafeStoreServer interface {
	mustEmbedUnimplementedStoreServer()
}

func RegisterStoreServer(s grpc.ServiceRegistrar, srv StoreServer) {
	// If the following call pancis, it indicates UnimplementedStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Store_ServiceDesc, srv)
}

func _Store_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Store_ServiceDesc is the grpc.ServiceDesc for Store service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Store_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.substreams.foundational_store.v1.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Store_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Store_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sf/substreams/foundational-store/service/v1/service.proto",
}
