// Protocol buffer definitions for the Substreams Foundational Store model.
// This package defines the core data structures used for storing and retrieving
// key-value pairs in a blockchain context with block-aware versioning.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/foundational-store/model/v2/model.proto

package pbmodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResponseCode indicates the result status of a get operation.
// Provides detailed information about whether a key was found,
// not found, or if there were other issues with the query.
type ResponseCode int32

const (
	// Default value, should not be used
	ResponseCode_RESPONSE_CODE_UNSPECIFIED ResponseCode = 0
	// Key exists and value was retrieved successfully
	ResponseCode_RESPONSE_CODE_FOUND ResponseCode = 1
	// Key does not exist at the requested block
	ResponseCode_RESPONSE_CODE_NOT_FOUND ResponseCode = 2
	// Key was deleted after finality (LIB) -> historical reference
	ResponseCode_RESPONSE_CODE_NOT_FOUND_FINALIZE ResponseCode = 4
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNSPECIFIED",
		1: "RESPONSE_CODE_FOUND",
		2: "RESPONSE_CODE_NOT_FOUND",
		4: "RESPONSE_CODE_NOT_FOUND_FINALIZE",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED":        0,
		"RESPONSE_CODE_FOUND":              1,
		"RESPONSE_CODE_NOT_FOUND":          2,
		"RESPONSE_CODE_NOT_FOUND_FINALIZE": 4,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_model_v2_model_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_model_v2_model_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{0}
}

// UpdatePolicy defines how a value should be merged with existing data.
// Used by Badger-backed stores to perform policy-aware read-modify-write operations.
type UpdatePolicy int32

const (
	// Default: replace existing value with new value
	UpdatePolicy_UPDATE_POLICY_SET UpdatePolicy = 0
	// Only set if key does not exist
	UpdatePolicy_UPDATE_POLICY_SET_IF_NOT_EXISTS UpdatePolicy = 1
	// Add numeric values (requires value_type to be numeric)
	UpdatePolicy_UPDATE_POLICY_ADD UpdatePolicy = 2
	// Keep minimum of existing and new value
	UpdatePolicy_UPDATE_POLICY_MIN UpdatePolicy = 3
	// Keep maximum of existing and new value
	UpdatePolicy_UPDATE_POLICY_MAX UpdatePolicy = 4
	// Append bytes to existing value
	UpdatePolicy_UPDATE_POLICY_APPEND UpdatePolicy = 5
	// Sum deltas (special ADD variant)
	UpdatePolicy_UPDATE_POLICY_SET_SUM UpdatePolicy = 6
)

// Enum value maps for UpdatePolicy.
var (
	UpdatePolicy_name = map[int32]string{
		0: "UPDATE_POLICY_SET",
		1: "UPDATE_POLICY_SET_IF_NOT_EXISTS",
		2: "UPDATE_POLICY_ADD",
		3: "UPDATE_POLICY_MIN",
		4: "UPDATE_POLICY_MAX",
		5: "UPDATE_POLICY_APPEND",
		6: "UPDATE_POLICY_SET_SUM",
	}
	UpdatePolicy_value = map[string]int32{
		"UPDATE_POLICY_SET":               0,
		"UPDATE_POLICY_SET_IF_NOT_EXISTS": 1,
		"UPDATE_POLICY_ADD":               2,
		"UPDATE_POLICY_MIN":               3,
		"UPDATE_POLICY_MAX":               4,
		"UPDATE_POLICY_APPEND":            5,
		"UPDATE_POLICY_SET_SUM":           6,
	}
)

func (x UpdatePolicy) Enum() *UpdatePolicy {
	p := new(UpdatePolicy)
	*p = x
	return p
}

func (x UpdatePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdatePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_model_v2_model_proto_enumTypes[1].Descriptor()
}

func (UpdatePolicy) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_model_v2_model_proto_enumTypes[1]
}

func (x UpdatePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatePolicy.Descriptor instead.
func (UpdatePolicy) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{1}
}

// Key represents a unique identifier for stored entries.
// The key is stored as raw bytes, allowing for flexible key formats
// including strings, hashes, or composite keys.
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Keys represents a collection of keys for batch operations.
type Keys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Key                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys) Reset() {
	*x = Keys{}
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{1}
}

func (x *Keys) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Entry represents a single key-value pair stored in the foundational store.
// Used by both consumer and sinker Substreams modules for data exchange.
// The entry contains a key and an arbitrary value wrapped in Any type.
// The update_policy specifies how the value should be merged with existing data.
// The value_type indicates the format of the value for proper deserialization.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	UpdatePolicy  UpdatePolicy           `protobuf:"varint,5,opt,name=update_policy,json=updatePolicy,proto3,enum=sf.substreams.foundational_store.model.v2.UpdatePolicy" json:"update_policy,omitempty"`
	ValueType     string                 `protobuf:"bytes,6,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"` // "int64", "bigint", "float64", "bigdecimal", "bytes"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entry) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetUpdatePolicy() UpdatePolicy {
	if x != nil {
		return x.UpdatePolicy
	}
	return UpdatePolicy_UPDATE_POLICY_SET
}

func (x *Entry) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

// SinkEntries represents a batch of entries to be stored by sinker modules.
// Contains multiple entries that should be stored atomically, with an option
// to only store entries if their keys don't already exist.
// The delete_prefixes field allows for efficient prefix-based deletion.
type SinkEntries struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Entries        []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	IfNotExist     bool                   `protobuf:"varint,2,opt,name=if_not_exist,json=ifNotExist,proto3" json:"if_not_exist,omitempty"`
	DeletePrefixes []string               `protobuf:"bytes,3,rep,name=delete_prefixes,json=deletePrefixes,proto3" json:"delete_prefixes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SinkEntries) Reset() {
	*x = SinkEntries{}
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkEntries) ProtoMessage() {}

func (x *SinkEntries) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkEntries.ProtoReflect.Descriptor instead.
func (*SinkEntries) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{3}
}

func (x *SinkEntries) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SinkEntries) GetIfNotExist() bool {
	if x != nil {
		return x.IfNotExist
	}
	return false
}

func (x *SinkEntries) GetDeletePrefixes() []string {
	if x != nil {
		return x.DeletePrefixes
	}
	return nil
}

// QueriedEntry represents the result of a get operation for a single key.
// Contains both the response status and the entry data (if found).
// Used by consumer Substreams modules to receive query results.
type QueriedEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=sf.substreams.foundational_store.model.v2.ResponseCode" json:"code,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueriedEntry) Reset() {
	*x = QueriedEntry{}
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueriedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueriedEntry) ProtoMessage() {}

func (x *QueriedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueriedEntry.ProtoReflect.Descriptor instead.
func (*QueriedEntry) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{4}
}

func (x *QueriedEntry) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNSPECIFIED
}

func (x *QueriedEntry) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// QueriedEntries represents the results of a batch get operation.
// Contains multiple QueriedEntry results for batch key lookups.
// Used by consumer Substreams modules for efficient bulk data retrieval.
type QueriedEntries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*QueriedEntry        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueriedEntries) Reset() {
	*x = QueriedEntries{}
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueriedEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueriedEntries) ProtoMessage() {}

func (x *QueriedEntries) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueriedEntries.ProtoReflect.Descriptor instead.
func (*QueriedEntries) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP(), []int{5}
}

func (x *QueriedEntries) GetEntries() []*QueriedEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_sf_substreams_foundational_store_model_v2_model_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_model_v2_model_proto_rawDesc = "" +
	"\n" +
	"5sf/substreams/foundational-store/model/v2/model.proto\x12)sf.substreams.foundational_store.model.v2\x1a\x19google/protobuf/any.proto\"\x1b\n" +
	"\x03Key\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"J\n" +
	"\x04Keys\x12B\n" +
	"\x04keys\x18\x01 \x03(\v2..sf.substreams.foundational_store.model.v2.KeyR\x04keys\"\xf8\x01\n" +
	"\x05Entry\x12@\n" +
	"\x03key\x18\x02 \x01(\v2..sf.substreams.foundational_store.model.v2.KeyR\x03key\x12*\n" +
	"\x05value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\\\n" +
	"\rupdate_policy\x18\x05 \x01(\x0e27.sf.substreams.foundational_store.model.v2.UpdatePolicyR\fupdatePolicy\x12\x1d\n" +
	"\n" +
	"value_type\x18\x06 \x01(\tR\tvalueTypeJ\x04\b\x01\x10\x02\"\xa4\x01\n" +
	"\vSinkEntries\x12J\n" +
	"\aentries\x18\x01 \x03(\v20.sf.substreams.foundational_store.model.v2.EntryR\aentries\x12 \n" +
	"\fif_not_exist\x18\x02 \x01(\bR\n" +
	"ifNotExist\x12'\n" +
	"\x0fdelete_prefixes\x18\x03 \x03(\tR\x0edeletePrefixes\"\xa3\x01\n" +
	"\fQueriedEntry\x12K\n" +
	"\x04code\x18\x01 \x01(\x0e27.sf.substreams.foundational_store.model.v2.ResponseCodeR\x04code\x12F\n" +
	"\x05entry\x18\x02 \x01(\v20.sf.substreams.foundational_store.model.v2.EntryR\x05entry\"c\n" +
	"\x0eQueriedEntries\x12Q\n" +
	"\aentries\x18\x02 \x03(\v27.sf.substreams.foundational_store.model.v2.QueriedEntryR\aentries*\x89\x01\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESPONSE_CODE_FOUND\x10\x01\x12\x1b\n" +
	"\x17RESPONSE_CODE_NOT_FOUND\x10\x02\x12$\n" +
	" RESPONSE_CODE_NOT_FOUND_FINALIZE\x10\x04*\xc4\x01\n" +
	"\fUpdatePolicy\x12\x15\n" +
	"\x11UPDATE_POLICY_SET\x10\x00\x12#\n" +
	"\x1fUPDATE_POLICY_SET_IF_NOT_EXISTS\x10\x01\x12\x15\n" +
	"\x11UPDATE_POLICY_ADD\x10\x02\x12\x15\n" +
	"\x11UPDATE_POLICY_MIN\x10\x03\x12\x15\n" +
	"\x11UPDATE_POLICY_MAX\x10\x04\x12\x18\n" +
	"\x14UPDATE_POLICY_APPEND\x10\x05\x12\x19\n" +
	"\x15UPDATE_POLICY_SET_SUM\x10\x06B\xed\x02\n" +
	"-com.sf.substreams.foundational_store.model.v2B\n" +
	"ModelProtoP\x01Zkgithub.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/model/v2;pbmodel\xa2\x02\x04SSFM\xaa\x02(Sf.Substreams.FoundationalStore.Model.V2\xca\x02(Sf\\Substreams\\FoundationalStore\\Model\\V2\xe2\x024Sf\\Substreams\\FoundationalStore\\Model\\V2\\GPBMetadata\xea\x02,Sf::Substreams::FoundationalStore::Model::V2b\x06proto3"

var (
	file_sf_substreams_foundational_store_model_v2_model_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_model_v2_model_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_model_v2_model_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_model_v2_model_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_model_v2_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_model_v2_model_proto_rawDesc), len(file_sf_substreams_foundational_store_model_v2_model_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_model_v2_model_proto_rawDescData
}

var file_sf_substreams_foundational_store_model_v2_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sf_substreams_foundational_store_model_v2_model_proto_goTypes = []any{
	(ResponseCode)(0),      // 0: sf.substreams.foundational_store.model.v2.ResponseCode
	(UpdatePolicy)(0),      // 1: sf.substreams.foundational_store.model.v2.UpdatePolicy
	(*Key)(nil),            // 2: sf.substreams.foundational_store.model.v2.Key
	(*Keys)(nil),           // 3: sf.substreams.foundational_store.model.v2.Keys
	(*Entry)(nil),          // 4: sf.substreams.foundational_store.model.v2.Entry
	(*SinkEntries)(nil),    // 5: sf.substreams.foundational_store.model.v2.SinkEntries
	(*QueriedEntry)(nil),   // 6: sf.substreams.foundational_store.model.v2.QueriedEntry
	(*QueriedEntries)(nil), // 7: sf.substreams.foundational_store.model.v2.QueriedEntries
	(*anypb.Any)(nil),      // 8: google.protobuf.Any
}
var file_sf_substreams_foundational_store_model_v2_model_proto_depIdxs = []int32{
	2, // 0: sf.substreams.foundational_store.model.v2.Keys.keys:type_name -> sf.substreams.foundational_store.model.v2.Key
	2, // 1: sf.substreams.foundational_store.model.v2.Entry.key:type_name -> sf.substreams.foundational_store.model.v2.Key
	8, // 2: sf.substreams.foundational_store.model.v2.Entry.value:type_name -> google.protobuf.Any
	1, // 3: sf.substreams.foundational_store.model.v2.Entry.update_policy:type_name -> sf.substreams.foundational_store.model.v2.UpdatePolicy
	4, // 4: sf.substreams.foundational_store.model.v2.SinkEntries.entries:type_name -> sf.substreams.foundational_store.model.v2.Entry
	0, // 5: sf.substreams.foundational_store.model.v2.QueriedEntry.code:type_name -> sf.substreams.foundational_store.model.v2.ResponseCode
	4, // 6: sf.substreams.foundational_store.model.v2.QueriedEntry.entry:type_name -> sf.substreams.foundational_store.model.v2.Entry
	6, // 7: sf.substreams.foundational_store.model.v2.QueriedEntries.entries:type_name -> sf.substreams.foundational_store.model.v2.QueriedEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_model_v2_model_proto_init() }
func file_sf_substreams_foundational_store_model_v2_model_proto_init() {
	if File_sf_substreams_foundational_store_model_v2_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_model_v2_model_proto_rawDesc), len(file_sf_substreams_foundational_store_model_v2_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_foundational_store_model_v2_model_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_model_v2_model_proto_depIdxs,
		EnumInfos:         file_sf_substreams_foundational_store_model_v2_model_proto_enumTypes,
		MessageInfos:      file_sf_substreams_foundational_store_model_v2_model_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_model_v2_model_proto = out.File
	file_sf_substreams_foundational_store_model_v2_model_proto_goTypes = nil
	file_sf_substreams_foundational_store_model_v2_model_proto_depIdxs = nil
}
