// Protocol buffer definitions for the Substreams Foundational Store remote feed.
// This package defines the ingest service used by external services to populate
// the foundational store directly over gRPC, as an alternative to running a
// Substreams sink. Data pushed through this service is considered already final.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/substreams/foundational-store/feed/v2/feed.proto

package pbfeed

import (
	v2 "github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/model/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetRequest carries the batch of entries to ingest.
type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entries to write, together with the if_not_exist flag.
	Entries       *v2.SinkEntries `protobuf:"bytes,1,opt,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetEntries() *v2.SinkEntries {
	if x != nil {
		return x.Entries
	}
	return nil
}

// SetResponse is returned once the entries have been persisted.
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescGZIP(), []int{1}
}

// SetReadyRequest carries the new readiness state to persist.
type SetReadyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the store should be considered ready to serve reads.
	Ready         bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReadyRequest) Reset() {
	*x = SetReadyRequest{}
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadyRequest) ProtoMessage() {}

func (x *SetReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadyRequest.ProtoReflect.Descriptor instead.
func (*SetReadyRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescGZIP(), []int{2}
}

func (x *SetReadyRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// SetReadyResponse is returned once the readiness state has been persisted.
type SetReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReadyResponse) Reset() {
	*x = SetReadyResponse{}
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadyResponse) ProtoMessage() {}

func (x *SetReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadyResponse.ProtoReflect.Descriptor instead.
func (*SetReadyResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescGZIP(), []int{3}
}

var File_sf_substreams_foundational_store_feed_v2_feed_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDesc = "" +
	"\n" +
	"3sf/substreams/foundational-store/feed/v2/feed.proto\x12(sf.substreams.foundational_store.feed.v2\x1a5sf/substreams/foundational-store/model/v2/model.proto\"^\n" +
	"\n" +
	"SetRequest\x12P\n" +
	"\aentries\x18\x01 \x01(\v26.sf.substreams.foundational_store.model.v2.SinkEntriesR\aentries\"\r\n" +
	"\vSetResponse\"'\n" +
	"\x0fSetReadyRequest\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\x12\n" +
	"\x10SetReadyResponse2\xfe\x01\n" +
	"\x04Feed\x12r\n" +
	"\x03Set\x124.sf.substreams.foundational_store.feed.v2.SetRequest\x1a5.sf.substreams.foundational_store.feed.v2.SetResponse\x12\x81\x01\n" +
	"\bSetReady\x129.sf.substreams.foundational_store.feed.v2.SetReadyRequest\x1a:.sf.substreams.foundational_store.feed.v2.SetReadyResponseB\xe5\x02\n" +
	",com.sf.substreams.foundational_store.feed.v2B\tFeedProtoP\x01Zigithub.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/feed/v2;pbfeed\xa2\x02\x04SSFF\xaa\x02'Sf.Substreams.FoundationalStore.Feed.V2\xca\x02'Sf\\Substreams\\FoundationalStore\\Feed\\V2\xe2\x023Sf\\Substreams\\FoundationalStore\\Feed\\V2\\GPBMetadata\xea\x02+Sf::Substreams::FoundationalStore::Feed::V2b\x06proto3"

var (
	file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDesc), len(file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDescData
}

var file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sf_substreams_foundational_store_feed_v2_feed_proto_goTypes = []any{
	(*SetRequest)(nil),       // 0: sf.substreams.foundational_store.feed.v2.SetRequest
	(*SetResponse)(nil),      // 1: sf.substreams.foundational_store.feed.v2.SetResponse
	(*SetReadyRequest)(nil),  // 2: sf.substreams.foundational_store.feed.v2.SetReadyRequest
	(*SetReadyResponse)(nil), // 3: sf.substreams.foundational_store.feed.v2.SetReadyResponse
	(*v2.SinkEntries)(nil),   // 4: sf.substreams.foundational_store.model.v2.SinkEntries
}
var file_sf_substreams_foundational_store_feed_v2_feed_proto_depIdxs = []int32{
	4, // 0: sf.substreams.foundational_store.feed.v2.SetRequest.entries:type_name -> sf.substreams.foundational_store.model.v2.SinkEntries
	0, // 1: sf.substreams.foundational_store.feed.v2.Feed.Set:input_type -> sf.substreams.foundational_store.feed.v2.SetRequest
	2, // 2: sf.substreams.foundational_store.feed.v2.Feed.SetReady:input_type -> sf.substreams.foundational_store.feed.v2.SetReadyRequest
	1, // 3: sf.substreams.foundational_store.feed.v2.Feed.Set:output_type -> sf.substreams.foundational_store.feed.v2.SetResponse
	3, // 4: sf.substreams.foundational_store.feed.v2.Feed.SetReady:output_type -> sf.substreams.foundational_store.feed.v2.SetReadyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_feed_v2_feed_proto_init() }
func file_sf_substreams_foundational_store_feed_v2_feed_proto_init() {
	if File_sf_substreams_foundational_store_feed_v2_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDesc), len(file_sf_substreams_foundational_store_feed_v2_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_substreams_foundational_store_feed_v2_feed_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_feed_v2_feed_proto_depIdxs,
		MessageInfos:      file_sf_substreams_foundational_store_feed_v2_feed_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_feed_v2_feed_proto = out.File
	file_sf_substreams_foundational_store_feed_v2_feed_proto_goTypes = nil
	file_sf_substreams_foundational_store_feed_v2_feed_proto_depIdxs = nil
}
