// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/foundational-store/service/v2/service.proto

package pbservice

import (
	v2 "github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/model/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest specifies the parameters for retrieving values from the store.
// Used by both Get and GetFirst operations to query the foundational store.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block number at which to query the data.
	// This ensures queries are performed against a specific point in the blockchain history.
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// The block hash for additional verification and fork-awareness.
	// Ensures the query is performed against the correct block in case of chain forks.
	BlockHash []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// The keys to retrieve from the store.
	// For Get: exact key matches are returned.
	// For GetFirst: the first key >= each requested key is returned (lexicographically).
	Keys          []*v2.Key `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *GetRequest) GetKeys() []*v2.Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

// GetResponse contains the results of a store query operation.
// Provides batch results for multiple keys with consistent block-level metadata.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the requested block has been processed by the store.
	// When false, some entries may not be available even if they should exist.
	BlockReached bool `protobuf:"varint,1,opt,name=block_reached,json=blockReached,proto3" json:"block_reached,omitempty"`
	// The query results for each requested key.
	// Each entry corresponds to one of the keys in the request, in the same order.
	Entries       *v2.QueriedEntries `protobuf:"bytes,2,opt,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetBlockReached() bool {
	if x != nil {
		return x.BlockReached
	}
	return false
}

func (x *GetResponse) GetEntries() *v2.QueriedEntries {
	if x != nil {
		return x.Entries
	}
	return nil
}

// SetRequest specifies entries to write to the store.
type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entries to write to the store.
	SinkEntries *v2.SinkEntries `protobuf:"bytes,1,opt,name=sink_entries,json=sinkEntries,proto3" json:"sink_entries,omitempty"`
	// The block number at which these entries are being written.
	BlockNumber   uint64 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetSinkEntries() *v2.SinkEntries {
	if x != nil {
		return x.SinkEntries
	}
	return nil
}

func (x *SetRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

// SetResponse contains the result of a SetAll operation.
type SetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of entries successfully written.
	EntriesWritten uint64 `protobuf:"varint,1,opt,name=entries_written,json=entriesWritten,proto3" json:"entries_written,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetEntriesWritten() uint64 {
	if x != nil {
		return x.EntriesWritten
	}
	return 0
}

// FlushRequest specifies the block up to which to persist data.
type FlushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block number up to which to flush (typically LIB).
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// Whether to use if_not_exist semantics when flushing.
	IfNotExist    bool `protobuf:"varint,2,opt,name=if_not_exist,json=ifNotExist,proto3" json:"if_not_exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{4}
}

func (x *FlushRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *FlushRequest) GetIfNotExist() bool {
	if x != nil {
		return x.IfNotExist
	}
	return false
}

// FlushResponse contains the result of a FlushUpToBlock operation.
type FlushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of entries flushed from cache to backing store.
	EntriesFlushed uint64 `protobuf:"varint,1,opt,name=entries_flushed,json=entriesFlushed,proto3" json:"entries_flushed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{5}
}

func (x *FlushResponse) GetEntriesFlushed() uint64 {
	if x != nil {
		return x.EntriesFlushed
	}
	return 0
}

// EvictRequest specifies the block number from which to evict data.
type EvictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block number at or above which to evict entries (reorg point).
	BlockNumber   uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRequest) Reset() {
	*x = EvictRequest{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRequest) ProtoMessage() {}

func (x *EvictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRequest.ProtoReflect.Descriptor instead.
func (*EvictRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{6}
}

func (x *EvictRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

// EvictResponse contains the result of an EvictUpToBlock operation.
type EvictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of entries evicted from the cache.
	EntriesEvicted uint64 `protobuf:"varint,1,opt,name=entries_evicted,json=entriesEvicted,proto3" json:"entries_evicted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvictResponse) Reset() {
	*x = EvictResponse{}
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictResponse) ProtoMessage() {}

func (x *EvictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictResponse.ProtoReflect.Descriptor instead.
func (*EvictResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP(), []int{7}
}

func (x *EvictResponse) GetEntriesEvicted() uint64 {
	if x != nil {
		return x.EntriesEvicted
	}
	return 0
}

var File_sf_substreams_foundational_store_service_v2_service_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_service_v2_service_proto_rawDesc = "" +
	"\n" +
	"9sf/substreams/foundational-store/service/v2/service.proto\x12+sf.substreams.foundational_store.service.v2\x1a\x19google/protobuf/any.proto\x1a5sf/substreams/foundational-store/model/v2/model.proto\"\x92\x01\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12B\n" +
	"\x04keys\x18\x03 \x03(\v2..sf.substreams.foundational_store.model.v2.KeyR\x04keys\"\x87\x01\n" +
	"\vGetResponse\x12#\n" +
	"\rblock_reached\x18\x01 \x01(\bR\fblockReached\x12S\n" +
	"\aentries\x18\x02 \x01(\v29.sf.substreams.foundational_store.model.v2.QueriedEntriesR\aentries\"\x8a\x01\n" +
	"\n" +
	"SetRequest\x12Y\n" +
	"\fsink_entries\x18\x01 \x01(\v26.sf.substreams.foundational_store.model.v2.SinkEntriesR\vsinkEntries\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\"6\n" +
	"\vSetResponse\x12'\n" +
	"\x0fentries_written\x18\x01 \x01(\x04R\x0eentriesWritten\"S\n" +
	"\fFlushRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12 \n" +
	"\fif_not_exist\x18\x02 \x01(\bR\n" +
	"ifNotExist\"8\n" +
	"\rFlushResponse\x12'\n" +
	"\x0fentries_flushed\x18\x01 \x01(\x04R\x0eentriesFlushed\"1\n" +
	"\fEvictRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"8\n" +
	"\rEvictResponse\x12'\n" +
	"\x0fentries_evicted\x18\x01 \x01(\x04R\x0eentriesEvicted2\x91\x05\n" +
	"\x05Store\x12x\n" +
	"\x03Get\x127.sf.substreams.foundational_store.service.v2.GetRequest\x1a8.sf.substreams.foundational_store.service.v2.GetResponse\x12}\n" +
	"\bGetFirst\x127.sf.substreams.foundational_store.service.v2.GetRequest\x1a8.sf.substreams.foundational_store.service.v2.GetResponse\x12{\n" +
	"\x06SetAll\x127.sf.substreams.foundational_store.service.v2.SetRequest\x1a8.sf.substreams.foundational_store.service.v2.SetResponse\x12\x87\x01\n" +
	"\x0eFlushUpToBlock\x129.sf.substreams.foundational_store.service.v2.FlushRequest\x1a:.sf.substreams.foundational_store.service.v2.FlushResponse\x12\x87\x01\n" +
	"\x0eEvictUpToBlock\x129.sf.substreams.foundational_store.service.v2.EvictRequest\x1a:.sf.substreams.foundational_store.service.v2.EvictResponseB\xfd\x02\n" +
	"/com.sf.substreams.foundational_store.service.v2B\fServiceProtoP\x01Zogithub.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/service/v2;pbservice\xa2\x02\x04SSFS\xaa\x02*Sf.Substreams.FoundationalStore.Service.V2\xca\x02*Sf\\Substreams\\FoundationalStore\\Service\\V2\xe2\x026Sf\\Substreams\\FoundationalStore\\Service\\V2\\GPBMetadata\xea\x02.Sf::Substreams::FoundationalStore::Service::V2b\x06proto3"

var (
	file_sf_substreams_foundational_store_service_v2_service_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_service_v2_service_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_service_v2_service_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_service_v2_service_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_service_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_service_v2_service_proto_rawDesc), len(file_sf_substreams_foundational_store_service_v2_service_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_service_v2_service_proto_rawDescData
}

var file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sf_substreams_foundational_store_service_v2_service_proto_goTypes = []any{
	(*GetRequest)(nil),        // 0: sf.substreams.foundational_store.service.v2.GetRequest
	(*GetResponse)(nil),       // 1: sf.substreams.foundational_store.service.v2.GetResponse
	(*SetRequest)(nil),        // 2: sf.substreams.foundational_store.service.v2.SetRequest
	(*SetResponse)(nil),       // 3: sf.substreams.foundational_store.service.v2.SetResponse
	(*FlushRequest)(nil),      // 4: sf.substreams.foundational_store.service.v2.FlushRequest
	(*FlushResponse)(nil),     // 5: sf.substreams.foundational_store.service.v2.FlushResponse
	(*EvictRequest)(nil),      // 6: sf.substreams.foundational_store.service.v2.EvictRequest
	(*EvictResponse)(nil),     // 7: sf.substreams.foundational_store.service.v2.EvictResponse
	(*v2.Key)(nil),            // 8: sf.substreams.foundational_store.model.v2.Key
	(*v2.QueriedEntries)(nil), // 9: sf.substreams.foundational_store.model.v2.QueriedEntries
	(*v2.SinkEntries)(nil),    // 10: sf.substreams.foundational_store.model.v2.SinkEntries
}
var file_sf_substreams_foundational_store_service_v2_service_proto_depIdxs = []int32{
	8,  // 0: sf.substreams.foundational_store.service.v2.GetRequest.keys:type_name -> sf.substreams.foundational_store.model.v2.Key
	9,  // 1: sf.substreams.foundational_store.service.v2.GetResponse.entries:type_name -> sf.substreams.foundational_store.model.v2.QueriedEntries
	10, // 2: sf.substreams.foundational_store.service.v2.SetRequest.sink_entries:type_name -> sf.substreams.foundational_store.model.v2.SinkEntries
	0,  // 3: sf.substreams.foundational_store.service.v2.Store.Get:input_type -> sf.substreams.foundational_store.service.v2.GetRequest
	0,  // 4: sf.substreams.foundational_store.service.v2.Store.GetFirst:input_type -> sf.substreams.foundational_store.service.v2.GetRequest
	2,  // 5: sf.substreams.foundational_store.service.v2.Store.SetAll:input_type -> sf.substreams.foundational_store.service.v2.SetRequest
	4,  // 6: sf.substreams.foundational_store.service.v2.Store.FlushUpToBlock:input_type -> sf.substreams.foundational_store.service.v2.FlushRequest
	6,  // 7: sf.substreams.foundational_store.service.v2.Store.EvictUpToBlock:input_type -> sf.substreams.foundational_store.service.v2.EvictRequest
	1,  // 8: sf.substreams.foundational_store.service.v2.Store.Get:output_type -> sf.substreams.foundational_store.service.v2.GetResponse
	1,  // 9: sf.substreams.foundational_store.service.v2.Store.GetFirst:output_type -> sf.substreams.foundational_store.service.v2.GetResponse
	3,  // 10: sf.substreams.foundational_store.service.v2.Store.SetAll:output_type -> sf.substreams.foundational_store.service.v2.SetResponse
	5,  // 11: sf.substreams.foundational_store.service.v2.Store.FlushUpToBlock:output_type -> sf.substreams.foundational_store.service.v2.FlushResponse
	7,  // 12: sf.substreams.foundational_store.service.v2.Store.EvictUpToBlock:output_type -> sf.substreams.foundational_store.service.v2.EvictResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_service_v2_service_proto_init() }
func file_sf_substreams_foundational_store_service_v2_service_proto_init() {
	if File_sf_substreams_foundational_store_service_v2_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_service_v2_service_proto_rawDesc), len(file_sf_substreams_foundational_store_service_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_substreams_foundational_store_service_v2_service_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_service_v2_service_proto_depIdxs,
		MessageInfos:      file_sf_substreams_foundational_store_service_v2_service_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_service_v2_service_proto = out.File
	file_sf_substreams_foundational_store_service_v2_service_proto_goTypes = nil
	file_sf_substreams_foundational_store_service_v2_service_proto_depIdxs = nil
}
