// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sf/substreams/foundational-store/service/v2/service.proto

package pbservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Store_Get_FullMethodName            = "/sf.substreams.foundational_store.service.v2.Store/Get"
	Store_GetFirst_FullMethodName       = "/sf.substreams.foundational_store.service.v2.Store/GetFirst"
	Store_SetAll_FullMethodName         = "/sf.substreams.foundational_store.service.v2.Store/SetAll"
	Store_FlushUpToBlock_FullMethodName = "/sf.substreams.foundational_store.service.v2.Store/FlushUpToBlock"
	Store_EvictUpToBlock_FullMethodName = "/sf.substreams.foundational_store.service.v2.Store/EvictUpToBlock"
)

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Store service provides the primary interface for interacting with the Substreams Foundational Store.
// This service offers block-aware key-value storage operations that are essential for
// building deterministic and fork-aware blockchain data processing pipelines.
type StoreClient interface {
	// Get retrieves one or more values from the store at a specific block.
	// Returns entries for all requested keys, with appropriate status codes for missing keys.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// GetFirst retrieves the first (lexicographically smallest) value that is greater than or equal to each requested key.
	// Useful for range queries and finding the next key in sorted order.
	GetFirst(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// SetAll writes multiple entries to the store at a specific block with policy-aware merging.
	// Used by BadgerBackedStore to persist operations from substreams tier2.
	SetAll(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// FlushUpToBlock persists all entries up to the specified block number (LIB) to the backing store.
	// Entries above this block remain in the ForkAware cache.
	FlushUpToBlock(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// EvictUpToBlock removes all entries at or above the specified block number (fork rollback).
	// Used to handle blockchain reorganizations.
	EvictUpToBlock(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Store_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetFirst(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Store_GetFirst_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) SetAll(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, Store_SetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) FlushUpToBlock(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, Store_FlushUpToBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) EvictUpToBlock(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictResponse)
	err := c.cc.Invoke(ctx, Store_EvictUpToBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
// All implementations must embed UnimplementedStoreServer
// for forward compatibility.
//
// Store service provides the primary interface for interacting with the Substreams Foundational Store.
// This service offers block-aware key-value storage operations that are essential for
// building deterministic and fork-aware blockchain data processing pipelines.
type StoreServer interface {
	// Get retrieves one or more values from the store at a specific block.
	// Returns entries for all requested keys, with appropriate status codes for missing keys.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// GetFirst retrieves the first (lexicographically smallest) value that is greater than or equal to each requested key.
	// Useful for range queries and finding the next key in sorted order.
	GetFirst(context.Context, *GetRequest) (*GetResponse, error)
	// SetAll writes multiple entries to the store at a specific block with policy-aware merging.
	// Used by BadgerBackedStore to persist operations from substreams tier2.
	SetAll(context.Context, *SetRequest) (*SetResponse, error)
	// FlushUpToBlock persists all entries up to the specified block number (LIB) to the backing store.
	// Entries above this block remain in the ForkAware cache.
	FlushUpToBlock(context.Context, *FlushRequest) (*FlushResponse, error)
	// EvictUpToBlock removes all entries at or above the specified block number (fork rollback).
	// Used to handle blockchain reorganizations.
	EvictUpToBlock(context.Context, *EvictRequest) (*EvictResponse, error)
	mustEmbedUnimplementedStoreServer()
}

// UnimplementedStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServer struct{}

func (UnimplementedStoreServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStoreServer) GetFirst(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirst not implemented")
}
func (UnimplementedStoreServer) SetAll(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAll not implemented")
}
func (UnimplementedStoreServer) FlushUpToBlock(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushUpToBlock not implemented")
}
func (UnimplementedStoreServer) EvictUpToBlock(context.Context, *EvictRequest) (*EvictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvictUpToBlock not implemented")
}
func (UnimplementedStoreServer) mustEmbedUnimplementedStoreServer() {}
func (UnimplementedStoreServer) testEmbeddedByValue()               {}

// UnsafeStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServer will
// result in compilation errors.
type UnsafeStoreServer interface {
	mustEmbedUnimplementedStoreServer()
}

func RegisterStoreServer(s grpc.ServiceRegistrar, srv StoreServer) {
	// If the following call pancis, it indicates UnimplementedStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Store_ServiceDesc, srv)
}

func _Store_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetFirst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetFirst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_GetFirst_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetFirst(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_SetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).SetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_SetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).SetAll(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_FlushUpToBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).FlushUpToBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_FlushUpToBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).FlushUpToBlock(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_EvictUpToBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).EvictUpToBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_EvictUpToBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).EvictUpToBlock(ctx, req.(*EvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Store_ServiceDesc is the grpc.ServiceDesc for Store service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Store_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.substreams.foundational_store.service.v2.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Store_Get_Handler,
		},
		{
			MethodName: "GetFirst",
			Handler:    _Store_GetFirst_Handler,
		},
		{
			MethodName: "SetAll",
			Handler:    _Store_SetAll_Handler,
		},
		{
			MethodName: "FlushUpToBlock",
			Handler:    _Store_FlushUpToBlock_Handler,
		},
		{
			MethodName: "EvictUpToBlock",
			Handler:    _Store_EvictUpToBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sf/substreams/foundational-store/service/v2/service.proto",
}
